### WEB SCRAPING ###

*Extracting the data of brand Tata of used cars from Cars24.com of three different locations.*

In [1]:
import pandas as pd
import requests
from bs4 import BeautifulSoup
import html5lib

In [2]:
url="https://www.cars24.com/buy-used-tata-cars-mumbai/"

In [3]:
r= requests.get(url)

In [4]:
response=r.status_code
response

200

In [5]:
soup=BeautifulSoup(r.content,'html5lib')

In [6]:
km_driven=[]
fuel_type=[]
transmission=[]
RTO=[]
j=soup.find_all('p',class_="sc-braxZu kvfdZL")
for i in j:
    if "km" in i.get_text():
        km=i.get_text()
        km_driven.append(km)
    elif "Diesel" in i.get_text() or "Petrol" in i.get_text() or "CNG" in i.get_text() or "Electric" in i.get_text():
        fuel=i.get_text()
        fuel_type.append(fuel)
    elif "Manual" in i.get_text() or "Auto" in i.get_text():
         t=i.get_text()
         transmission.append(t)
    elif "MH" in i.get_text():
         R=i.get_text()
         RTO.append(R)     
    
print(km_driven)
print(fuel_type)
print(transmission)
print(RTO)
print(len(km_driven),len(fuel_type),len(transmission),len(RTO))

['63.58k km', '67.39k km', '35.91k km', '3.09k km', '54.57k km', '7.33k km', '27.24k km', '13.94k km', '42.04k km', '22.28k km', '30.23k km', '51.35k km', '15.37k km', '28.63k km', '21.03k km', '33.02k km', '54.77k km', '31.09k km', '75.74k km', '15.66k km']
['Diesel', 'Diesel', 'Petrol', 'Petrol', 'Diesel', 'Petrol', 'Petrol', 'Petrol', 'Petrol', 'Petrol', 'Diesel', 'CNG', 'Petrol', 'Petrol', 'CNG', 'CNG', 'Petrol', 'Petrol', 'CNG', 'Petrol']
['Manual', 'Manual', 'Manual', 'Manual', 'Manual', 'Manual', 'Auto', 'Auto', 'Auto', 'Auto', 'Manual', 'Manual', 'Manual', 'Auto', 'Manual', 'Manual', 'Auto', 'Auto', 'Manual', 'Manual']
['MH-04', 'MH-47', 'MH-02', 'MH-04', 'MH-12', 'MH-48', 'MH-01', 'MH-04', 'MH-02', 'MH-47', 'MH-01', 'MH-15', 'MH-47', 'MH-04', 'MH-47', 'MH-05', 'MH-04', 'MH-05', 'MH-05', 'MH-04']
20 20 20 20

In [7]:
car_name=[]
names=soup.find_all('span',class_="sc-braxZu kjFjan")
for i in names:
    car_name.append(i.text)
print(len(car_name))
print(car_name)

20
['2021 Tata NEXON', '2017 Tata TIGOR', '2021 Tata ALTROZ', '2024 Tata NEXON', '2021 Tata Harrier', '2024 Tata PUNCH', '2021 Tata TIGOR', '2018 Tata Tiago', '2023 Tata ALTROZ', '2019 Tata TIGOR', '2022 Tata ALTROZ', '2022 Tata TIGOR', '2021 Tata Tiago', '2018 Tata Tiago', '2020 Tata Tiago', '2022 Tata TIGOR', '2019 Tata NEXON', '2020 Tata NEXON', '2022 Tata TIGOR', '2022 Tata NEXON']

In [8]:
price=[]
prices=soup.find_all('p',class_="sc-braxZu cyPhJl")
for i in prices:
    price.append(i.text)
print(len(price))
print(price)

22
['Account ', '', '₹7.80 lakh', '₹3.92 lakh', '₹4.41 lakh', '₹10.80 lakh', '₹12.26 lakh', '₹6.25 lakh', '₹5.13 lakh', '₹3.95 lakh', '₹7.31 lakh', '₹4.65 lakh', '₹6.83 lakh', '₹5.59 lakh', '₹4.27 lakh', '₹3.85 lakh', '₹4.90 lakh', '₹5.96 lakh', '₹4.92 lakh', '₹7.46 lakh', '₹5.64 lakh', '₹7.95 lakh']

In [9]:
car_price=[]
car_price=price[2:22]
print(car_price)
print(len(car_price))

['₹7.80 lakh', '₹3.92 lakh', '₹4.41 lakh', '₹10.80 lakh', '₹12.26 lakh', '₹6.25 lakh', '₹5.13 lakh', '₹3.95 lakh', '₹7.31 lakh', '₹4.65 lakh', '₹6.83 lakh', '₹5.59 lakh', '₹4.27 lakh', '₹3.85 lakh', '₹4.90 lakh', '₹5.96 lakh', '₹4.92 lakh', '₹7.46 lakh', '₹5.64 lakh', '₹7.95 lakh']
20

In [10]:
location=[]
locations=soup.find_all('div',class_="styles_hubAddress__URioy")
for i in locations:
    location.append(i.text)
print(location)
print(len(location))

[' Mulund West, Mumbai ', ' Mulund West, Mumbai ', ' Thakur Village Kandivali E Mumbai', ' Regency Anantam, Dombivli East', ' Goregaon, Mumbai', ' Goregaon, Mumbai', ' Korum Mall, Thane West', ' Seawood\n', ' Seawood\n', ' Regency Anantam, Dombivli East', ' Regency Anantam, Dombivli East', ' Korum Mall, Thane West', ' Thakur Village Kandivali E Mumbai', ' Seawood\n', ' Regency Anantam, Dombivli East', ' Thakur Village Kandivali E Mumbai', ' Korum Mall, Thane West', ' Korum Mall, Thane West', ' Seawood\n', ' Goregaon, Mumbai']
20

In [11]:
data=pd.DataFrame({'car_name':car_name,'price':car_price,'RTO':RTO,'km_driven':km_driven,'fuel_type':fuel_type,'transmission':transmission,'location':location})
data

,car_name,price,RTO,km_driven,fuel_type,transmission,location
0,2021 Tata NEXON,₹7.80 lakh,MH-04,63.58k km,Diesel,Manual,"Mulund West, Mumbai"
1,2017 Tata TIGOR,₹3.92 lakh,MH-47,67.39k km,Diesel,Manual,"Mulund West, Mumbai"
2,2021 Tata ALTROZ,₹4.41 lakh,MH-02,35.91k km,Petrol,Manual,Thakur Village Kandivali E Mumbai
3,2024 Tata NEXON,₹10.80 lakh,MH-04,3.09k km,Petrol,Manual,"Regency Anantam, Dombivli East"
4,2021 Tata Harrier,₹12.26 lakh,MH-12,54.57k km,Diesel,Manual,"Goregaon, Mumbai"
5,2024 Tata PUNCH,₹6.25 lakh,MH-48,7.33k km,Petrol,Manual,"Goregaon, Mumbai"
6,2021 Tata TIGOR,₹5.13 lakh,MH-01,27.24k km,Petrol,Auto,"Korum Mall, Thane West"
7,2018 Tata Tiago,₹3.95 lakh,MH-04,13.94k km,Petrol,Auto,Seawood\n
8,2023 Tata ALTROZ,₹7.31 lakh,MH-02,42.04k km,Petrol,Auto,Seawood\n
9,2019 Tata TIGOR,₹4.65 lakh,MH-47,22.28k km,Petrol,Auto,"Regency Anantam, Dombivli East"
10,2022 Tata ALTROZ,₹6.83 lakh,MH-01,30.23k km,Diesel,Manual,"Regency Anantam, Dombivli East"
11,2022 Tata TIGOR,₹5.59 lakh,MH-15,51.35k km,CNG,Manual,"Korum Mall, Thane West"
12,2021 Tata Tiago,₹4.27 lakh,MH-47,15.37k km,Petrol,Manual,Thakur Village Kandivali E Mumbai
13,2018 Tata Tiago,₹3.85 lakh,MH-04,28.63k km,Petrol,Auto,Seawood\n
14,2020 Tata Tiago,₹4.90 lakh,MH-47,21.03k km,CNG,Manual,"Regency Anantam, Dombivli East"
15,2022 Tata TIGOR,₹5.96 lakh,MH-05,33.02k km,CNG,Manual,Thakur Village Kandivali E Mumbai
16,2019 Tata NEXON,₹4.92 lakh,MH-04,54.77k km,Petrol,Auto,"Korum Mall, Thane West"
17,2020 Tata NEXON,₹7.46 lakh,MH-05,31.09k km,Petrol,Auto,"Korum Mall, Thane West"
18,2022 Tata TIGOR,₹5.64 lakh,MH-05,75.74k km,CNG,Manual,Seawood\n
19,2022 Tata NEXON,₹7.95 lakh,MH-04,15.66k km,Petrol,Manual,"Goregaon, Mumbai"

In [12]:
data.to_csv('cars24.csv')

In [13]:
url='https://www.cars24.com/buy-used-cars-bangalore/'
r=requests.get(url)
response=r.status_code
response

200

In [14]:
soup=BeautifulSoup(r.content,'html5lib')

In [15]:
km_driven=[]
fuel_type=[]
transmission=[]
RTO=[]
j=soup.find_all('p',class_="sc-braxZu kvfdZL")
for i in j:
    if "km" in i.get_text():
        km=i.get_text()
        km_driven.append(km)
    elif "Diesel" in i.get_text() or "Petrol" in i.get_text() or "CNG" in i.get_text() or "Electric" in i.get_text():
        fuel=i.get_text()
        fuel_type.append(fuel)
    elif "Manual" in i.get_text() or "Auto" in i.get_text():
         t=i.get_text()
         transmission.append(t)
    elif "KA" in i.get_text():
         R=i.get_text()
         RTO.append(R)     
    
print(km_driven)
print(fuel_type)
print(transmission)
print(RTO)
print(len(km_driven),len(fuel_type),len(transmission),len(RTO))

['60.40k km', '32.66k km', '64.89k km', '8.18k km', '80.89k km', '56.31k km', '71.64k km', '31.74k km', '53.13k km', '31.06k km', '78.92k km', '84.89k km', '99.95k km', '44.63k km', '41.05k km', '24.53k km', '31.55k km', '1.0L km', '64.33k km', '14.76k km']
['Diesel', 'Petrol', 'Diesel', 'Diesel', 'CNG', 'Petrol', 'Petrol', 'Petrol', 'Petrol', 'Petrol', 'Petrol', 'Petrol', 'Petrol', 'Petrol', 'Petrol', 'Petrol', 'Petrol', 'Petrol', 'Diesel', 'Petrol']
['Auto', 'Auto', 'Manual', 'Auto', 'Manual', 'Manual', 'Manual', 'Manual', 'Auto', 'Manual', 'Manual', 'Manual', 'Manual', 'Manual', 'Auto', 'Manual', 'Auto', 'Auto', 'Manual', 'Auto']
['KA-02', 'KA-03', 'KA-03', 'KA-53', 'KA-02', 'KA-05', 'KA-51', 'KA-03', 'KA-05', 'KA-41', 'KA-01', 'KA-20', 'KA-53', 'KA-05', 'KA-03', 'KA-09', 'KA-05', 'KA-01', 'KA-53', 'KA-51']
20 20 20 20

In [16]:
carname=[]
name=soup.find_all('span',class_="sc-braxZu kjFjan")
for i in name:
    carname.append(i.text)
print(len(carname)) 
print(carname)

20
['2022 Mahindra XUV700', '2020 BMW X1', '2021 Tata Safari', '2023 MG GLOSTER', '2014 Toyota Etios', '2017 Tata TIGOR', '2016 Maruti Baleno', '2016 Renault Kwid', '2020 Maruti Ertiga', '2018 Hyundai Grand i10', '2016 Maruti Swift Dzire', '2016 Hyundai Creta', '2014 Hyundai i20', '2019 Ford Ecosport', '2017 Maruti Wagon R 1.0', '2023 KIA SONET', '2020 Tata NEXON', '2018 Toyota YARIS', '2020 Tata NEXON', '2023 Mahindra XUV700']

In [17]:
price=[]
prices=soup.find_all('p',class_="sc-braxZu cyPhJl")
for i in prices:
    price.append(i.text)
print(len(price))
print(price)

22
['Account ', '', '₹21.99 lakh', '₹28.45 lakh', '₹16.65 lakh', '₹36.45 lakh', '₹4.00 lakh', '₹4.78 lakh', '₹5.29 lakh', '₹2.63 lakh', '₹8.93 lakh', '₹5.29 lakh', '₹5.12 lakh', '₹7.40 lakh', '₹4.15 lakh', '₹7.31 lakh', '₹3.97 lakh', '₹8.91 lakh', '₹7.49 lakh', '₹5.43 lakh', '₹8.34 lakh', '₹21.40 lakh']

In [18]:
car_price=[]
car_price=price[2:22]
print(car_price)
print(len(car_price))

['₹21.99 lakh', '₹28.45 lakh', '₹16.65 lakh', '₹36.45 lakh', '₹4.00 lakh', '₹4.78 lakh', '₹5.29 lakh', '₹2.63 lakh', '₹8.93 lakh', '₹5.29 lakh', '₹5.12 lakh', '₹7.40 lakh', '₹4.15 lakh', '₹7.31 lakh', '₹3.97 lakh', '₹8.91 lakh', '₹7.49 lakh', '₹5.43 lakh', '₹8.34 lakh', '₹21.40 lakh']
20

In [19]:
location=[]
locations=soup.find_all('div',class_="styles_hubAddress__URioy")
for i in locations:
    location.append(i.text)
print(location)
print(len(location))

[' CARS24 ELITE Hub, MS Ramaiah North City', ' CARS24 ELITE Hub, MS Ramaiah North City', ' CARS24 ELITE Hub, MS Ramaiah North City', ' CARS24 ELITE Hub, MS Ramaiah North City', ' Gandhi Nagar', ' Gandhi Nagar', ' Gandhi Nagar', ' Nexus Whitefield', ' Whitefield Main Road, Bhoruka Tech Park, Bengaluru', ' Nexus Whitefield', ' Whitefield Main Road, Bhoruka Tech Park, Bengaluru', ' Nexus Whitefield', ' Whitefield Main Road, Bhoruka Tech Park, Bengaluru', ' GT World Mall, Bengaluru', ' Bellahalli, Bengaluru', ' Vaishnavi Sapphire Centre, Yeswanthpur', ' Gandhi Nagar', ' Nexus Whitefield', ' GT World Mall, Bengaluru', ' GT World Mall, Bengaluru']
20

In [20]:
data=pd.DataFrame({'car_name':carname,'price':car_price,'RTO':RTO,'km_driven':km_driven,'fuel_type':fuel_type,'transmission':transmission,'location':location})
data

,car_name,price,RTO,km_driven,fuel_type,transmission,location
0,2022 Mahindra XUV700,₹21.99 lakh,KA-02,60.40k km,Diesel,Auto,"CARS24 ELITE Hub, MS Ramaiah North City"
1,2020 BMW X1,₹28.45 lakh,KA-03,32.66k km,Petrol,Auto,"CARS24 ELITE Hub, MS Ramaiah North City"
2,2021 Tata Safari,₹16.65 lakh,KA-03,64.89k km,Diesel,Manual,"CARS24 ELITE Hub, MS Ramaiah North City"
3,2023 MG GLOSTER,₹36.45 lakh,KA-53,8.18k km,Diesel,Auto,"CARS24 ELITE Hub, MS Ramaiah North City"
4,2014 Toyota Etios,₹4.00 lakh,KA-02,80.89k km,CNG,Manual,Gandhi Nagar
5,2017 Tata TIGOR,₹4.78 lakh,KA-05,56.31k km,Petrol,Manual,Gandhi Nagar
6,2016 Maruti Baleno,₹5.29 lakh,KA-51,71.64k km,Petrol,Manual,Gandhi Nagar
7,2016 Renault Kwid,₹2.63 lakh,KA-03,31.74k km,Petrol,Manual,Nexus Whitefield
8,2020 Maruti Ertiga,₹8.93 lakh,KA-05,53.13k km,Petrol,Auto,"Whitefield Main Road, Bhoruka Tech Park, Beng..."
9,2018 Hyundai Grand i10,₹5.29 lakh,KA-41,31.06k km,Petrol,Manual,Nexus Whitefield
10,2016 Maruti Swift Dzire,₹5.12 lakh,KA-01,78.92k km,Petrol,Manual,"Whitefield Main Road, Bhoruka Tech Park, Beng..."
11,2016 Hyundai Creta,₹7.40 lakh,KA-20,84.89k km,Petrol,Manual,Nexus Whitefield
12,2014 Hyundai i20,₹4.15 lakh,KA-53,99.95k km,Petrol,Manual,"Whitefield Main Road, Bhoruka Tech Park, Beng..."
13,2019 Ford Ecosport,₹7.31 lakh,KA-05,44.63k km,Petrol,Manual,"GT World Mall, Bengaluru"
14,2017 Maruti Wagon R 1.0,₹3.97 lakh,KA-03,41.05k km,Petrol,Auto,"Bellahalli, Bengaluru"
15,2023 KIA SONET,₹8.91 lakh,KA-09,24.53k km,Petrol,Manual,"Vaishnavi Sapphire Centre, Yeswanthpur"
16,2020 Tata NEXON,₹7.49 lakh,KA-05,31.55k km,Petrol,Auto,Gandhi Nagar
17,2018 Toyota YARIS,₹5.43 lakh,KA-01,1.0L km,Petrol,Auto,Nexus Whitefield
18,2020 Tata NEXON,₹8.34 lakh,KA-53,64.33k km,Diesel,Manual,"GT World Mall, Bengaluru"
19,2023 Mahindra XUV700,₹21.40 lakh,KA-51,14.76k km,Petrol,Auto,"GT World Mall, Bengaluru"

In [21]:
data.to_csv('cars24_bangalore.csv')

In [22]:
url='https://www.cars24.com/buy-used-cars-new-delhi/'
r=requests.get(url)
response=r.status_code
response

200

In [23]:
soup=BeautifulSoup(r.content,'html5lib')

In [24]:
location=[]
locations=soup.find_all('div',class_="styles_hubAddress__URioy")
for i in locations:
    location.append(i.text)
print(location)
print(len(location))

[' Metro Walk, Rohini, New Delhi', ' Metro Walk, Rohini, New Delhi', ' Rajouri Garden', ' Rajouri Garden', ' Metro Walk, Rohini, New Delhi', ' Metro Walk, Rohini, New Delhi', ' Metro Walk, Rohini, New Delhi', ' Metro Walk, Rohini, New Delhi', ' Metro Walk, Rohini, New Delhi', ' Metro Walk, Rohini, New Delhi', ' Metro Walk, Rohini, New Delhi', ' Metro Walk, Rohini, New Delhi', ' Metro Walk, Rohini, New Delhi', ' Rajouri Garden', ' Metro Walk, Rohini, New Delhi', ' Metro Walk, Rohini, New Delhi', ' Metro Walk, Rohini, New Delhi', ' Rajouri Garden', ' Metro Walk, Rohini, New Delhi', ' Rajouri Garden', ' CARS24 ELITE Hub, Surajpur Site-4, Greater Noida', ' CARS24 ELITE Hub, Surajpur Site-4, Greater Noida', ' KW Delhi 6, Raj Nagar Extension, Ghaziabad', ' CARS24 ELITE Hub, Malibu Town, Sector 47', ' CARS24 ELITE Hub, Surajpur Site-4, Greater Noida', ' CARS24 ELITE Hub, Malibu Town, Sector 47', ' CARS24 ELITE Hub, Surajpur Site-4, Greater Noida', ' CARS24 ELITE Hub, Malibu Town, Sector 47', ' CARS24 ELITE Hub, Malibu Town, Sector 47', ' CARS24 ELITE Hub, Malibu Town, Sector 47', ' CARS24 ELITE Hub, Surajpur Site-4, Greater Noida', ' CARS24 ELITE Hub, Surajpur Site-4, Greater Noida', ' CARS24 ELITE Hub, Malibu Town, Sector 47', ' CARS24 ELITE Hub, Malibu Town, Sector 47', ' Piyush Mahendra Mall, opp. Dussehra Ground, NIT - 3', ' Sector-18, Noida', ' CARS24 ELITE Hub, Surajpur Site-4, Greater Noida', ' M3M Urbana, Golf Course Ext., Gurugram', ' Sector-18, Noida', ' CARS24 ELITE Hub, Malibu Town, Sector 47']
40

In [25]:
km_driven=[]
fuel_type=[]
transmission=[]
RTO=[]
j=soup.find_all('p',class_="sc-braxZu kvfdZL")
for i in j:
    if "km" in i.get_text():
        km=i.get_text()
        km_driven.append(km)
    elif "Diesel" in i.get_text() or "Petrol" in i.get_text() or "CNG" in i.get_text() or "Electric" in i.get_text():
        fuel=i.get_text()
        fuel_type.append(fuel)
    elif "Manual" in i.get_text() or "Auto" in i.get_text():
         t=i.get_text()
         transmission.append(t)
    elif "DL" in i.get_text() or "HR" in i.get_text() or "UP" in i.get_text():
         R=i.get_text()
         RTO.append(R)     
    
print(km_driven)
print(fuel_type)
print(transmission)
print(RTO)
print(len(km_driven),len(fuel_type),len(transmission),len(RTO))

['31.76k km', '51.55k km', '61.73k km', '65.41k km', '33.21k km', '23.67k km', '43.05k km', '56.79k km', '57.13k km', '31.96k km', '57.64k km', '53.31k km', '67.82k km', '33.71k km', '71.29k km', '30.91k km', '29.03k km', '33.73k km', '23.59k km', '7.76k km', '38.94k km', '29.00k km', '99.90k km', '35.94k km', '17.40k km', '17.56k km', '16.31k km', '49.32k km', '17.33k km', '24.19k km', '12.35k km', '7.68k km', '3.24k km', '79.81k km', '91.21k km', '28.31k km', '67.29k km', '43.24k km', '12.62k km', '70.98k km']
['Petrol', 'Petrol', 'Petrol', 'Petrol', 'Petrol', 'Petrol', 'Petrol', 'Petrol', 'Petrol', 'Petrol', 'Petrol', 'Petrol', 'Petrol', 'Petrol', 'Petrol', 'Petrol', 'Petrol', 'Petrol', 'Petrol', 'Petrol', 'Diesel', 'Petrol', 'Petrol', 'Petrol', 'Petrol', 'Petrol', 'Petrol', 'Diesel', 'Diesel', 'Diesel', 'Petrol', 'Petrol', 'Electric', 'Diesel', 'Petrol', 'CNG', 'Diesel', 'Petrol', 'CNG', 'Diesel']
['Manual', 'Manual', 'Manual', 'Manual', 'Manual', 'Manual', 'Manual', 'Auto', 'Manual', 'Manual', 'Manual', 'Manual', 'Manual', 'Manual', 'Manual', 'Manual', 'Manual', 'Manual', 'Manual', 'Manual', 'Auto', 'Auto', 'Manual', 'Auto', 'Manual', 'Manual', 'Auto', 'Auto', 'Auto', 'Auto', 'Auto', 'Auto', 'Auto', 'Auto', 'Manual', 'Manual', 'Manual', 'Manual', 'Manual', 'Auto']
['DL-1C', 'DL-12', 'DL-7C', 'DL-3C', 'DL-5C', 'HR-02', 'DL-10', 'DL-3C', 'DL-4C', 'DL-7C', 'DL-8C', 'HR-51', 'DL-8C', 'DL-14', 'DL-2C', 'DL-5C', 'DL-12', 'DL-4C', 'HR-87', 'DL-14', 'UP-16', 'HR-98', 'DL-3C', 'HR-87', 'DL-3C', 'HR-85', 'DL-3C', 'HR-13', 'HR-29', 'HR-51', 'HR-98', 'HR-98', 'DL-1G', 'HR-87', 'HR-26', 'DL-3C', 'DL-3C', 'HR-26', 'DL-7C', 'HR-26']
40 40 40 40

In [26]:
carname=[]
name=soup.find_all('span',class_="sc-braxZu kjFjan")
for i in name:
    carname.append(i.text)
print(len(carname)) 
print(carname)

40
['2017 Renault Kwid', '2012 Maruti Wagon R 1.0', '2021 Nissan MAGNITE', '2021 KIA SELTOS', '2023 Tata PUNCH', '2019 Hyundai Elite i20', '2020 MG HECTOR', '2023 Maruti FRONX', '2020 Hyundai VENUE', '2022 Mahindra Thar', '2021 Volkswagen Polo', '2017 Tata TIGOR', '2016 Hyundai Elite i20', '2022 Maruti Swift', '2021 Maruti Ertiga', '2022 Tata PUNCH', '2013 Maruti Alto 800', '2018 Maruti Swift', '2023 Maruti FRONX', '2024 KIA SONET', '2023 Mahindra Thar', '2024 Hyundai Creta', '2018 Datsun Go', '2022 KIA SELTOS', '2022 KIA SELTOS', '2022 Mahindra SCORPIO-N', '2022 Jeep Compass', '2019 Landrover DISCOVERY SPORT', '2022 Mercedes Benz GLA Class', '2022 Mercedes Benz GLS', '2024 Hyundai Creta', '2024 Hyundai Creta', '2023 BMW iX', '2021 KIA CARNIVAL', '2018 Maruti Dzire', '2020 Maruti Ertiga', '2022 Mahindra XUV700', '2019 Maruti Alto', '2024 Maruti Swift', '2019 Honda CRV']

In [27]:
price=[]
prices=soup.find_all('p',class_="sc-braxZu cyPhJl")
for i in prices:
    price.append(i.text)
print(len(price))
print(price)

42
['Account ', '', '₹1.99 lakh', '₹1.52 lakh', '₹4.12 lakh', '₹8.17 lakh', '₹4.75 lakh', '₹4.76 lakh', '₹8.44 lakh', '₹7.38 lakh', '₹5.53 lakh', '₹10.59 lakh', '₹4.75 lakh', '₹3.16 lakh', '₹3.69 lakh', '₹5.25 lakh', '₹7.99 lakh', '₹4.75 lakh', '₹1.70 lakh', '₹4.49 lakh', '₹7.99 lakh', '₹6.99 lakh', '₹15.00 lakh', '₹17.30 lakh', '₹1.95 lakh', '₹14.00 lakh', '₹12.90 lakh', '₹19.00 lakh', '₹19.00 lakh', '₹29.00 lakh', '₹39.00 lakh', '₹1.00 Crore', '₹18.40 lakh', '₹18.35 lakh', '₹75.00 lakh', '₹20.90 lakh', '₹3.82 lakh', '₹7.51 lakh', '₹14.25 lakh', '₹2.35 lakh', '₹6.40 lakh', '₹15.50 lakh']

In [28]:
car_price=[]
car_price=price[2:42]
print(car_price)
print(len(car_price))

['₹1.99 lakh', '₹1.52 lakh', '₹4.12 lakh', '₹8.17 lakh', '₹4.75 lakh', '₹4.76 lakh', '₹8.44 lakh', '₹7.38 lakh', '₹5.53 lakh', '₹10.59 lakh', '₹4.75 lakh', '₹3.16 lakh', '₹3.69 lakh', '₹5.25 lakh', '₹7.99 lakh', '₹4.75 lakh', '₹1.70 lakh', '₹4.49 lakh', '₹7.99 lakh', '₹6.99 lakh', '₹15.00 lakh', '₹17.30 lakh', '₹1.95 lakh', '₹14.00 lakh', '₹12.90 lakh', '₹19.00 lakh', '₹19.00 lakh', '₹29.00 lakh', '₹39.00 lakh', '₹1.00 Crore', '₹18.40 lakh', '₹18.35 lakh', '₹75.00 lakh', '₹20.90 lakh', '₹3.82 lakh', '₹7.51 lakh', '₹14.25 lakh', '₹2.35 lakh', '₹6.40 lakh', '₹15.50 lakh']
40

In [29]:
data=pd.DataFrame({'car_name':carname,'price':car_price,'RTO':RTO,'km_driven':km_driven,'fuel_type':fuel_type,'transmission':transmission,'location':location})
data

,car_name,price,RTO,km_driven,fuel_type,transmission,location
0,2017 Renault Kwid,₹1.99 lakh,DL-1C,31.76k km,Petrol,Manual,"Metro Walk, Rohini, New Delhi"
1,2012 Maruti Wagon R 1.0,₹1.52 lakh,DL-12,51.55k km,Petrol,Manual,"Metro Walk, Rohini, New Delhi"
2,2021 Nissan MAGNITE,₹4.12 lakh,DL-7C,61.73k km,Petrol,Manual,Rajouri Garden
3,2021 KIA SELTOS,₹8.17 lakh,DL-3C,65.41k km,Petrol,Manual,Rajouri Garden
4,2023 Tata PUNCH,₹4.75 lakh,DL-5C,33.21k km,Petrol,Manual,"Metro Walk, Rohini, New Delhi"
5,2019 Hyundai Elite i20,₹4.76 lakh,HR-02,23.67k km,Petrol,Manual,"Metro Walk, Rohini, New Delhi"
6,2020 MG HECTOR,₹8.44 lakh,DL-10,43.05k km,Petrol,Manual,"Metro Walk, Rohini, New Delhi"
7,2023 Maruti FRONX,₹7.38 lakh,DL-3C,56.79k km,Petrol,Auto,"Metro Walk, Rohini, New Delhi"
8,2020 Hyundai VENUE,₹5.53 lakh,DL-4C,57.13k km,Petrol,Manual,"Metro Walk, Rohini, New Delhi"
9,2022 Mahindra Thar,₹10.59 lakh,DL-7C,31.96k km,Petrol,Manual,"Metro Walk, Rohini, New Delhi"
10,2021 Volkswagen Polo,₹4.75 lakh,DL-8C,57.64k km,Petrol,Manual,"Metro Walk, Rohini, New Delhi"
11,2017 Tata TIGOR,₹3.16 lakh,HR-51,53.31k km,Petrol,Manual,"Metro Walk, Rohini, New Delhi"
12,2016 Hyundai Elite i20,₹3.69 lakh,DL-8C,67.82k km,Petrol,Manual,"Metro Walk, Rohini, New Delhi"
13,2022 Maruti Swift,₹5.25 lakh,DL-14,33.71k km,Petrol,Manual,Rajouri Garden
14,2021 Maruti Ertiga,₹7.99 lakh,DL-2C,71.29k km,Petrol,Manual,"Metro Walk, Rohini, New Delhi"
15,2022 Tata PUNCH,₹4.75 lakh,DL-5C,30.91k km,Petrol,Manual,"Metro Walk, Rohini, New Delhi"
16,2013 Maruti Alto 800,₹1.70 lakh,DL-12,29.03k km,Petrol,Manual,"Metro Walk, Rohini, New Delhi"
17,2018 Maruti Swift,₹4.49 lakh,DL-4C,33.73k km,Petrol,Manual,Rajouri Garden
18,2023 Maruti FRONX,₹7.99 lakh,HR-87,23.59k km,Petrol,Manual,"Metro Walk, Rohini, New Delhi"
19,2024 KIA SONET,₹6.99 lakh,DL-14,7.76k km,Petrol,Manual,Rajouri Garden
20,2023 Mahindra Thar,₹15.00 lakh,UP-16,38.94k km,Diesel,Auto,"CARS24 ELITE Hub, Surajpur Site-4, Greater Noida"
21,2024 Hyundai Creta,₹17.30 lakh,HR-98,29.00k km,Petrol,Auto,"CARS24 ELITE Hub, Surajpur Site-4, Greater Noida"
22,2018 Datsun Go,₹1.95 lakh,DL-3C,99.90k km,Petrol,Manual,"KW Delhi 6, Raj Nagar Extension, Ghaziabad"
23,2022 KIA SELTOS,₹14.00 lakh,HR-87,35.94k km,Petrol,Auto,"CARS24 ELITE Hub, Malibu Town, Sector 47"
24,2022 KIA SELTOS,₹12.90 lakh,DL-3C,17.40k km,Petrol,Manual,"CARS24 ELITE Hub, Surajpur Site-4, Greater Noida"
25,2022 Mahindra SCORPIO-N,₹19.00 lakh,HR-85,17.56k km,Petrol,Manual,"CARS24 ELITE Hub, Malibu Town, Sector 47"
26,2022 Jeep Compass,₹19.00 lakh,DL-3C,16.31k km,Petrol,Auto,"CARS24 ELITE Hub, Surajpur Site-4, Greater Noida"
27,2019 Landrover DISCOVERY SPORT,₹29.00 lakh,HR-13,49.32k km,Diesel,Auto,"CARS24 ELITE Hub, Malibu Town, Sector 47"
28,2022 Mercedes Benz GLA Class,₹39.00 lakh,HR-29,17.33k km,Diesel,Auto,"CARS24 ELITE Hub, Malibu Town, Sector 47"
29,2022 Mercedes Benz GLS,₹1.00 Crore,HR-51,24.19k km,Diesel,Auto,"CARS24 ELITE Hub, Malibu Town, Sector 47"
30,2024 Hyundai Creta,₹18.40 lakh,HR-98,12.35k km,Petrol,Auto,"CARS24 ELITE Hub, Surajpur Site-4, Greater Noida"
31,2024 Hyundai Creta,₹18.35 lakh,HR-98,7.68k km,Petrol,Auto,"CARS24 ELITE Hub, Surajpur Site-4, Greater Noida"
32,2023 BMW iX,₹75.00 lakh,DL-1G,3.24k km,Electric,Auto,"CARS24 ELITE Hub, Malibu Town, Sector 47"
33,2021 KIA CARNIVAL,₹20.90 lakh,HR-87,79.81k km,Diesel,Auto,"CARS24 ELITE Hub, Malibu Town, Sector 47"
34,2018 Maruti Dzire,₹3.82 lakh,HR-26,91.21k km,Petrol,Manual,"Piyush Mahendra Mall, opp. Dussehra Ground, N..."
35,2020 Maruti Ertiga,₹7.51 lakh,DL-3C,28.31k km,CNG,Manual,"Sector-18, Noida"
36,2022 Mahindra XUV700,₹14.25 lakh,DL-3C,67.29k km,Diesel,Manual,"CARS24 ELITE Hub, Surajpur Site-4, Greater Noida"
37,2019 Maruti Alto,₹2.35 lakh,HR-26,43.24k km,Petrol,Manual,"M3M Urbana, Golf Course Ext., Gurugram"
38,2024 Maruti Swift,₹6.40 lakh,DL-7C,12.62k km,CNG,Manual,"Sector-18, Noida"
39,2019 Honda CRV,₹15.50 lakh,HR-26,70.98k km,Diesel,Auto,"CARS24 ELITE Hub, Malibu Town, Sector 47"

In [30]:
data.to_csv('cars24_delhi.csv')