### WEB SCRAPING ###

*Extracting the data of brand Tata of used cars from Cars24.com of three different locations.*

In [1]:
import pandas as pd
import requests
from bs4 import BeautifulSoup
import html5lib

In [2]:
url="https://www.cars24.com/buy-used-tata-cars-mumbai/"

In [3]:
r= requests.get(url)

In [4]:
response=r.status_code
response

200

In [5]:
soup=BeautifulSoup(r.content,'html5lib')

In [6]:
soup

<!DOCTYPE html>

In [7]:
km_driven=[]
fuel_type=[]
transmission=[]
RTO=[]
j=soup.find_all('p',class_="sc-braxZu kvfdZL")
for i in j:
    if "km" in i.get_text():
        km=i.get_text()
        km_driven.append(km)
    elif "Diesel" in i.get_text() or "Petrol" in i.get_text() or "CNG" in i.get_text() or "Electric" in i.get_text():
        fuel=i.get_text()
        fuel_type.append(fuel)
    elif "Manual" in i.get_text() or "Auto" in i.get_text():
         t=i.get_text()
         transmission.append(t)
    elif "MH" in i.get_text():
         R=i.get_text()
         RTO.append(R)     
    
print(km_driven)
print(fuel_type)
print(transmission)
print(RTO)
print(len(km_driven),len(fuel_type),len(transmission),len(RTO))

['67.39k km', '35.91k km', '54.57k km', '73.18k km', '49.14k km', '7.33k km', '27.24k km', '22.28k km', '42.04k km', '51.35k km', '13.94k km', '30.23k km', '15.37k km', '28.63k km', '3.09k km', '21.03k km', '75.74k km', '54.77k km', '33.02k km', '31.09k km']
['Diesel', 'Petrol', 'Diesel', 'Petrol', 'Petrol', 'Petrol', 'Petrol', 'Petrol', 'Petrol', 'CNG', 'Petrol', 'Diesel', 'Petrol', 'Petrol', 'Petrol', 'CNG', 'CNG', 'Petrol', 'CNG', 'Petrol']
['Manual', 'Manual', 'Manual', 'Manual', 'Manual', 'Manual', 'Auto', 'Auto', 'Auto', 'Manual', 'Auto', 'Manual', 'Manual', 'Auto', 'Manual', 'Manual', 'Manual', 'Auto', 'Manual', 'Auto']
['MH-47', 'MH-02', 'MH-12', 'MH-46', 'MH-46', 'MH-48', 'MH-01', 'MH-47', 'MH-02', 'MH-15', 'MH-04', 'MH-01', 'MH-47', 'MH-04', 'MH-04', 'MH-47', 'MH-05', 'MH-04', 'MH-05', 'MH-05']
20 20 20 20

In [8]:
car_name=[]
names=soup.find_all('span',class_="sc-braxZu kjFjan")
for i in names:
    car_name.append(i.text)
print(len(car_name))
print(car_name)

20
['2017 Tata TIGOR', '2021 Tata ALTROZ', '2021 Tata Harrier', '2017 Tata Tiago', '2017 Tata NEXON', '2024 Tata PUNCH', '2021 Tata TIGOR', '2019 Tata TIGOR', '2023 Tata ALTROZ', '2022 Tata TIGOR', '2018 Tata Tiago', '2022 Tata ALTROZ', '2021 Tata Tiago', '2018 Tata Tiago', '2024 Tata NEXON', '2020 Tata Tiago', '2022 Tata TIGOR', '2019 Tata NEXON', '2022 Tata TIGOR', '2020 Tata NEXON']

In [9]:
price=[]
prices=soup.find_all('p',class_="sc-braxZu cyPhJl")
for i in prices:
    price.append(i.text)
print(len(price))
print(price)

22
['Account ', '', '₹3.92 lakh', '₹4.66 lakh', '₹12.26 lakh', '₹3.00 lakh', '₹4.94 lakh', '₹6.25 lakh', '₹5.13 lakh', '₹4.90 lakh', '₹7.31 lakh', '₹5.59 lakh', '₹3.95 lakh', '₹6.83 lakh', '₹4.27 lakh', '₹3.97 lakh', '₹11.00 lakh', '₹4.90 lakh', '₹5.64 lakh', '₹4.92 lakh', '₹5.96 lakh', '₹7.46 lakh']

In [10]:
car_price=[]
car_price=price[2:22]
print(car_price)
print(len(car_price))

['₹3.92 lakh', '₹4.66 lakh', '₹12.26 lakh', '₹3.00 lakh', '₹4.94 lakh', '₹6.25 lakh', '₹5.13 lakh', '₹4.90 lakh', '₹7.31 lakh', '₹5.59 lakh', '₹3.95 lakh', '₹6.83 lakh', '₹4.27 lakh', '₹3.97 lakh', '₹11.00 lakh', '₹4.90 lakh', '₹5.64 lakh', '₹4.92 lakh', '₹5.96 lakh', '₹7.46 lakh']
20

In [11]:
location=[]
locations=soup.find_all('div',class_="styles_hubAddress__URioy")
for i in locations:
    location.append(i.text)
print(location)
print(len(location))

[' Mulund West, Mumbai ', ' Thakur Village Kandivali E Mumbai', ' Goregaon, Mumbai', ' Mulund West, Mumbai ', ' Goregaon, Mumbai', ' Goregaon, Mumbai', ' Korum Mall, Thane West', ' Regency Anantam, Dombivli East', ' Seawood\n', ' Korum Mall, Thane West', ' Seawood\n', ' Regency Anantam, Dombivli East', ' Thakur Village Kandivali E Mumbai', ' Seawood\n', ' Regency Anantam, Dombivli East', ' Regency Anantam, Dombivli East', ' Seawood\n', ' Korum Mall, Thane West', ' Thakur Village Kandivali E Mumbai', ' Korum Mall, Thane West']
20

In [12]:
data=pd.DataFrame({'car_name':car_name,'price':car_price,'RTO':RTO,'km_driven':km_driven,'fuel_type':fuel_type,'transmission':transmission,'location':location})
data

,car_name,price,RTO,km_driven,fuel_type,transmission,location
0,2017 Tata TIGOR,₹3.92 lakh,MH-47,67.39k km,Diesel,Manual,"Mulund West, Mumbai"
1,2021 Tata ALTROZ,₹4.66 lakh,MH-02,35.91k km,Petrol,Manual,Thakur Village Kandivali E Mumbai
2,2021 Tata Harrier,₹12.26 lakh,MH-12,54.57k km,Diesel,Manual,"Goregaon, Mumbai"
3,2017 Tata Tiago,₹3.00 lakh,MH-46,73.18k km,Petrol,Manual,"Mulund West, Mumbai"
4,2017 Tata NEXON,₹4.94 lakh,MH-46,49.14k km,Petrol,Manual,"Goregaon, Mumbai"
5,2024 Tata PUNCH,₹6.25 lakh,MH-48,7.33k km,Petrol,Manual,"Goregaon, Mumbai"
6,2021 Tata TIGOR,₹5.13 lakh,MH-01,27.24k km,Petrol,Auto,"Korum Mall, Thane West"
7,2019 Tata TIGOR,₹4.90 lakh,MH-47,22.28k km,Petrol,Auto,"Regency Anantam, Dombivli East"
8,2023 Tata ALTROZ,₹7.31 lakh,MH-02,42.04k km,Petrol,Auto,Seawood\n
9,2022 Tata TIGOR,₹5.59 lakh,MH-15,51.35k km,CNG,Manual,"Korum Mall, Thane West"
10,2018 Tata Tiago,₹3.95 lakh,MH-04,13.94k km,Petrol,Auto,Seawood\n
11,2022 Tata ALTROZ,₹6.83 lakh,MH-01,30.23k km,Diesel,Manual,"Regency Anantam, Dombivli East"
12,2021 Tata Tiago,₹4.27 lakh,MH-47,15.37k km,Petrol,Manual,Thakur Village Kandivali E Mumbai
13,2018 Tata Tiago,₹3.97 lakh,MH-04,28.63k km,Petrol,Auto,Seawood\n
14,2024 Tata NEXON,₹11.00 lakh,MH-04,3.09k km,Petrol,Manual,"Regency Anantam, Dombivli East"
15,2020 Tata Tiago,₹4.90 lakh,MH-47,21.03k km,CNG,Manual,"Regency Anantam, Dombivli East"
16,2022 Tata TIGOR,₹5.64 lakh,MH-05,75.74k km,CNG,Manual,Seawood\n
17,2019 Tata NEXON,₹4.92 lakh,MH-04,54.77k km,Petrol,Auto,"Korum Mall, Thane West"
18,2022 Tata TIGOR,₹5.96 lakh,MH-05,33.02k km,CNG,Manual,Thakur Village Kandivali E Mumbai
19,2020 Tata NEXON,₹7.46 lakh,MH-05,31.09k km,Petrol,Auto,"Korum Mall, Thane West"

In [13]:
data.to_csv('cars24.csv')

In [14]:
url='https://www.cars24.com/buy-used-cars-bangalore/'
r=requests.get(url)
response=r.status_code
response

200

In [15]:
soup=BeautifulSoup(r.content,'html5lib')
soup

<!DOCTYPE html>
<html lang="en"><head><meta charset="utf-8"/><meta content="width=device-width, initial-scale=1, maximum-scale=5, user-scalable=yes" name="viewport"/><link as="image" href="https://media.cars24.com/india/car-catalog/clp/luxe_frame.png" rel="preload"/><link as="image" fetchpriority="high" href="https://media.cars24.com/india/cms/prod/banners/root/2025/02/18/dff4bd12-e42e-4b62-9354-3c5e429e5c1c-emi1.webp?w=100&amp;dpr=3" rel="preload"/><link data-precedence="next" href="https://assets.cars24.com/production/catalog-web-in/250915070318/_next/static/css/2bfc31bca40d7e0d.css" rel="stylesheet"/><link data-precedence="next" href="https://assets.cars24.com/production/catalog-web-in/250915070318/_next/static/css/4c165078a60bc99b.css" rel="stylesheet"/><link data-precedence="next" href="https://assets.cars24.com/production/catalog-web-in/250915070318/_next/static/css/0f56f3a62ea24a99.css" rel="stylesheet"/><link data-precedence="next" href="https://assets.cars24.com/production/catalog-web-in/250915070318/_next/static/css/92bebad41c9dfad0.css" rel="stylesheet"/><link data-precedence="next" href="https://assets.cars24.com/production/catalog-web-in/250915070318/_next/static/css/f210f3de0d0c59f6.css" rel="stylesheet"/><link data-precedence="next" href="https://assets.cars24.com/production/catalog-web-in/250915070318/_next/static/css/a041b41b8b19eba9.css" rel="stylesheet"/><link data-precedence="next" href="https://assets.cars24.com/production/catalog-web-in/250915070318/_next/static/css/04d85bc0ea4bf438.css" rel="stylesheet"/><link data-precedence="next" href="https://assets.cars24.com/production/catalog-web-in/250915070318/_next/static/css/f349509ec6c23a5f.css" rel="stylesheet"/><link data-precedence="next" href="https://assets.cars24.com/production/catalog-web-in/250915070318/_next/static/css/11296da54b128758.css" rel="stylesheet"/><link data-precedence="next" href="https://assets.cars24.com/production/catalog-web-in/250915070318/_next/static/css/0db3c9b1be12ae8c.css" rel="stylesheet"/><link data-precedence="next" href="https://assets.cars24.com/production/catalog-web-in/250915070318/_next/static/css/7cc7d7611e600fdc.css" rel="stylesheet"/><link data-precedence="next" href="https://assets.cars24.com/production/catalog-web-in/250915070318/_next/static/css/08eed280d85004d9.css" rel="stylesheet"/><link data-precedence="next" href="https://assets.cars24.com/production/catalog-web-in/250915070318/_next/static/css/4d70946f48a75205.css" rel="stylesheet"/><link data-precedence="next" href="https://assets.cars24.com/production/catalog-web-in/250915070318/_next/static/css/90cedd059d6c9ff9.css" rel="stylesheet"/><link data-precedence="next" href="https://assets.cars24.com/production/catalog-web-in/250915070318/_next/static/css/836eb861b47ffd43.css" rel="stylesheet"/><link data-precedence="next" href="https://assets.cars24.com/production/catalog-web-in/250915070318/_next/static/css/981970c32166e68c.css" rel="stylesheet"/><link data-precedence="next" href="https://assets.cars24.com/production/catalog-web-in/250915070318/_next/static/css/0d44b4cf0660fb9b.css" rel="stylesheet"/><link data-precedence="next" href="https://assets.cars24.com/production/catalog-web-in/250915070318/_next/static/css/b03bf2e8d3fa4e54.css" rel="stylesheet"/><link data-precedence="next" href="https://assets.cars24.com/production/catalog-web-in/250915070318/_next/static/css/b67fd353ff415181.css" rel="stylesheet"/><link data-precedence="next" href="https://assets.cars24.com/production/catalog-web-in/250915070318/_next/static/css/3c4ceee8e474adc9.css" rel="stylesheet"/><link data-precedence="next" href="https://assets.cars24.com/production/catalog-web-in/250915070318/_next/static/css/fc5b25d887b10f69.css" rel="stylesheet"/><link data-precedence="next" href="https://assets.cars24.com/production/catalog-web-in/250915070318/_next/static/css/a9732ae5f5cd7d9a.css" rel="stylesheet"/><link data-precedence="next" href="https://assets.cars24.com/production/catalog-web-in/250915070318/_next/static/css/51b7d6402ef75353.css" rel="stylesheet"/><link data-precedence="next" href="https://assets.cars24.com/production/catalog-web-in/250915070318/_next/static/css/3b9b86505f0db102.css" rel="stylesheet"/><link data-precedence="next" href="https://assets.cars24.com/production/catalog-web-in/250915070318/_next/static/css/9f210550016aa5b0.css" rel="stylesheet"/><link data-precedence="next" href="https://assets.cars24.com/production/catalog-web-in/250915070318/_next/static/css/851deb3e11c4e1c8.css" rel="stylesheet"/><link as="style" data-precedence="dynamic" href="https://assets.cars24.com/production/catalog-web-in/250915070318/_next/static/css/7ec1d74e0d424e4e.css" rel="stylesheet"/><link as="style" data-precedence="dynamic" href="https://assets.cars24.com/production/catalog-web-in/250915070318/_next/static/css/47cde6cb9ef97f48.css" rel="stylesheet"/><link as="style" data-precedence="dynamic" href="https://assets.cars24.com/production/catalog-web-in/250915070318/_next/static/css/02c34bc9fdc1ded7.css" rel="stylesheet"/><link as="style" data-precedence="dynamic" href="https://assets.cars24.com/production/catalog-web-in/250915070318/_next/static/css/f30bdbc02f846385.css" rel="stylesheet"/><link as="style" data-precedence="dynamic" href="https://assets.cars24.com/production/catalog-web-in/250915070318/_next/static/css/552a833f22545dfe.css" rel="stylesheet"/><link as="script" fetchpriority="low" href="https://assets.cars24.com/production/catalog-web-in/250915070318/_next/static/chunks/webpack-0258d8a1c62a4c9f.js" rel="preload"/><script async="" src="https://assets.cars24.com/production/catalog-web-in/250915070318/_next/static/chunks/1dd3208c-015fc21e435b8db5.js"></script><script async="" src="https://assets.cars24.com/production/catalog-web-in/250915070318/_next/static/chunks/1528-91d3f5b35dd59512.js"></script><script async="" src="https://assets.cars24.com/production/catalog-web-in/250915070318/_next/static/chunks/main-app-b785dae62bcd5af3.js"></script><script async="" src="https://assets.cars24.com/production/catalog-web-in/250915070318/_next/static/chunks/32278-2962f0df41e362bd.js"></script><script async="" src="https://assets.cars24.com/production/catalog-web-in/250915070318/_next/static/chunks/22147-10716e29dd63ea52.js"></script><script async="" src="https://assets.cars24.com/production/catalog-web-in/250915070318/_next/static/chunks/app/layout-6e21e37010ee7d7d.js"></script><script async="" src="https://assets.cars24.com/production/catalog-web-in/250915070318/_next/static/chunks/77695-debf32a62c56802c.js"></script><script async="" src="https://assets.cars24.com/production/catalog-web-in/250915070318/_next/static/chunks/21144-4a827b65b150c9af.js"></script><script async="" src="https://assets.cars24.com/production/catalog-web-in/250915070318/_next/static/chunks/40588-ba98c8be9ca14fe4.js"></script><script async="" src="https://assets.cars24.com/production/catalog-web-in/250915070318/_next/static/chunks/20417-6f942afc8acbf7c8.js"></script><script async="" src="https://assets.cars24.com/production/catalog-web-in/250915070318/_next/static/chunks/54527-e591553470046e32.js"></script><script async="" src="https://assets.cars24.com/production/catalog-web-in/250915070318/_next/static/chunks/82664-0753b6b516140c5a.js"></script><script async="" src="https://assets.cars24.com/production/catalog-web-in/250915070318/_next/static/chunks/61155-80be47db9e365dbb.js"></script><script async="" src="https://assets.cars24.com/production/catalog-web-in/250915070318/_next/static/chunks/18150-8ad0cae56d0d343a.js"></script><script async="" src="https://assets.cars24.com/production/catalog-web-in/250915070318/_next/static/chunks/3155-67e355439435f1e9.js"></script><script async="" src="https://assets.cars24.com/production/catalog-web-in/250915070318/_next/static/chunks/1445-14963d9a0a6d63f4.js"></script><script async="" src="https://assets.cars24.com/production/catalog-web-in/250915070318/_next/static/chunks/30700-2dad08d63a4772a9.js"></script><script async="" src="https://assets.cars24.com/production/catalog-web-in/250915070318/_next/static/chunks/63014-8d14eab64782cfac.js"></script><script async="" src="https://assets.cars24.com/production/catalog-web-in/250915070318/_next/static/chunks/app/desktop/layout-79652247be3716d3.js"></script><script async="" src="https://assets.cars24.com/production/catalog-web-in/250915070318/_next/static/chunks/45338-304665ee63de9d6d.js"></script><script async="" src="https://assets.cars24.com/production/catalog-web-in/250915070318/_next/static/chunks/98544-d41f0fc8f583b45b.js"></script><script async="" src="https://assets.cars24.com/production/catalog-web-in/250915070318/_next/static/chunks/48284-997cbd881471d102.js"></script><script async="" src="https://assets.cars24.com/production/catalog-web-in/250915070318/_next/static/chunks/58395-d8fc299aaf98b61a.js"></script><script async="" src="https://assets.cars24.com/production/catalog-web-in/250915070318/_next/static/chunks/90252-8cab28f760827762.js"></script><script async="" src="https://assets.cars24.com/production/catalog-web-in/250915070318/_next/static/chunks/33765-2c91d7972d043817.js"></script><script async="" src="https://assets.cars24.com/production/catalog-web-in/250915070318/_next/static/chunks/20371-7554148c3ff8743c.js"></script><script async="" src="https://assets.cars24.com/production/catalog-web-in/250915070318/_next/static/chunks/69535-ea1ed085d0d9b5d6.js"></script><script async="" src="https://assets.cars24.com/production/catalog-web-in/250915070318/_next/static/chunks/51220-a31c433d0a9c94a3.js"></script><script async="" src="https://assets.cars24.com/production/catalog-web-in/250915070318/_next/static/chunks/54169-6c72c34f6b1a0373.js"></script><script async="" src="https://assets.cars24.com/production/catalog-web-in/250915070318/_next/static/chunks/23924-62e459ec058eb7b5.js"></script><script async="" src="https://assets.cars24.com/production/catalog-web-in/250915070318/_next/static/chunks/96643-57e72adc5dc45299.js"></script><script async="" src="https://assets.cars24.com/production/catalog-web-in/250915070318/_next/static/chunks/app/desktop/buy-used-cars-listing/page-0c176af8f812e589.js"></script><link as="script" href="https://www.googletagmanager.com/gtm.js?id=GTM-P3C9RJ" rel="preload"/><link crossorigin="" href="https://assets.cars24.com" rel="preconnect"/><link crossorigin="" href="https://media.cars24.com" rel="preconnect"/><link crossorigin="" href="https://www.googletagmanager.com" rel="preconnect"/><link crossorigin="" href="https://www.google-analytics.com" rel="preconnect"/><link href="https://connect.facebook.net" rel="dns-prefetch"/><link href="https://analytics.twitter.com" rel="dns-prefetch"/><link href="https://www.facebook.com" rel="dns-prefetch"/><link href="https://www.google.com" rel="dns-prefetch"/><link href="https://www.google.co.in" rel="dns-prefetch"/><link href="https://googleads.g.doubleclick.net" rel="dns-prefetch"/><link href="https://t.co" rel="dns-prefetch"/><link href="https://static.ads-twitter.com" rel="dns-prefetch"/><link href="https://tracking.cars24.com" rel="dns-prefetch"/><link href="https://gumi.criteo.com" rel="dns-prefetch"/><link href="https://dynamic.criteo.com" rel="dns-prefetch"/><link href="https://tr.snapchat.com" rel="dns-prefetch"/><link href="https://pixel.tapad.com" rel="dns-prefetch"/><link href="https://sslwidget.criteo.com" rel="dns-prefetch"/><title>Used Cars in Bangalore - 2344 Second Hand Cars starting from ₹0.62 lakh | CARS24</title><meta content="Get GST discount on used cars in Bangalore at CARS24. Starting from just ₹0.62 lakh, explore popular second hand car models like  &lt;strong&gt;Tata NEXON&lt;/strong&gt;, &lt;strong&gt;Renault Kwid&lt;/strong&gt;,  and &lt;strong&gt;Maruti Swift&lt;/strong&gt; - all available with easy financing options." name="description"/><meta content="Buy used cars in Bangalore, buy used cars online in Bangalore, Used Cars Online in Bangalore, Second Hand Cars in Bangalore, Second Hand Cars Online in Bangalore, Buy Second hand cars online in Bangalore, Certified Used Cars in Bangalore, Pre-owned cars online in Bangalore" name="keywords"/><meta content="INDEX,FOLLOW" name="robots"/><link href="https://www.cars24.com/buy-used-cars-bangalore/" rel="canonical"/><meta content="Used Cars in Bangalore - 2344 Second Hand Cars starting from ₹0.62 lakh | CARS24" property="og:title"/><meta content="Get GST discount on used cars in Bangalore at CARS24. Starting from just ₹0.62 lakh, explore popular second hand car models like  &lt;strong&gt;Tata NEXON&lt;/strong&gt;, &lt;strong&gt;Renault Kwid&lt;/strong&gt;,  and &lt;strong&gt;Maruti Swift&lt;/strong&gt; - all available with easy financing options." property="og:description"/><meta content="https://www.cars24.com/buy-used-cars-bangalore/" property="og:url"/><meta content="CARS24" property="og:site_name"/><meta content="https://assets.cars24.com/static/c2b-website/thumbnails/1-1/buy-car.png" property="og:image"/><meta content="https://assets.cars24.com/static/c2b-website/thumbnails/1-91-1/buy-car.png" property="og:image"/><meta content="https://assets.cars24.com/static/c2b-website/thumbnails/16-9/buy-car.png" property="og:image"/><meta content="website" property="og:type"/><meta content="summary_large_image" name="twitter:card"/><meta content="Used Cars in Bangalore - 2344 Second Hand Cars starting from ₹0.62 lakh | CARS24" name="twitter:title"/><meta content="Get GST discount on used cars in Bangalore at CARS24. Starting from just ₹0.62 lakh, explore popular second hand car models like  &lt;strong&gt;Tata NEXON&lt;/strong&gt;, &lt;strong&gt;Renault Kwid&lt;/strong&gt;,  and &lt;strong&gt;Maruti Swift&lt;/strong&gt; - all available with easy financing options." name="twitter:description"/><meta content="https://assets.cars24.com/static/c2b-website/thumbnails/1-1/buy-car.png" name="twitter:image"/><meta content="https://assets.cars24.com/static/c2b-website/thumbnails/1-91-1/buy-car.png" name="twitter:image"/><meta content="https://assets.cars24.com/static/c2b-website/thumbnails/16-9/buy-car.png" name="twitter:image"/><link href="https://assets.cars24.com/static/c2b-website/favicon.ico" rel="shortcut icon"/><meta name="next-size-adjust"/><script>(self.__next_s=self.__next_s||[]).push([0,{"children":"\n                    {\n                        (function () {\n                            function handleMessage(event) {\n                                try {\n                                    let message = event.data;\n                                    if (typeof message === \"string\") {\n                                        try {\n                                            message = JSON.parse(message);\n                                        } catch (error) {\n                                            return;\n                                        }\n                                    }\n                                    if (message && message.name === \"APP_LOGIN_EVENT\") {\n                                        window.WEBVIEW_EVENT_NAME = message.name;\n                                        if (message.authToken) {\n                                            window.APP_AUTH_TOKEN = message.authToken;\n                                        }\n                                    }\n                                } catch (error) {\n                                    //\n                                }\n                            }\n                            window.addEventListener(\"message\", handleMessage);\n\n                            window.onunload = function () {\n                                window.removeEventListener(\"message\", handleMessage);\n                            };\n                        })()\n                    }\n                ","id":"app-login-event-handler"}])</script><script nomodule="" src="https://assets.cars24.com/production/catalog-web-in/250915070318/_next/static/chunks/polyfills-42372ed130431b0a.js"></script><style data-styled="" data-styled-version="6.1.12">.jEqeKQ{font-size:var(--font-size-150);font-weight:var(--regular);line-height:var(--line-height-150);color:var(--grey-900);margin:0;padding:0;text-align:left;text-transform:none;text-decoration:none;}/*!sc*/
.cyPhJl{font-size:var(--font-size-250);font-weight:var(--semibold);line-height:var(--line-height-250);color:var(--grey-900);margin:0;padding:0;text-align:left;text-transform:none;text-decoration:none;}/*!sc*/
.AgQbP{font-size:var(--font-size-200);font-weight:var(--medium);line-height:var(--line-height-200);color:var(--grey-900);margin:0;padding:0;text-align:left;text-transform:none;text-decoration:none;}/*!sc*/
.dughoY{font-size:var(--font-size-200);font-weight:var(--regular);line-height:var(--line-height-200);color:var(--grey-900);margin:0;padding:0;text-align:left;text-transform:none;text-decoration:none;}/*!sc*/
.lmmumg{font-size:var(--font-size-150);font-weight:var(--regular);line-height:var(--line-height-150);color:var(--grey-500);margin:0;padding:0;text-align:left;text-transform:none;text-decoration:none;}/*!sc*/
.kjFjan{font-size:var(--font-size-250);font-weight:var(--medium);line-height:var(--line-height-250);color:var(--grey-900);margin:0;padding:0;text-align:left;text-transform:none;text-decoration:none;}/*!sc*/
.kvfdZL{font-size:var(--font-size-150);font-weight:var(--medium);line-height:var(--line-height-150);color:var(--grey-500);margin:0;padding:0;text-align:left;text-transform:none;text-decoration:none;}/*!sc*/
.gbxhkm{font-size:var(--font-size-200);font-weight:var(--regular);line-height:var(--line-height-200);color:var(--grey-500);margin:0;padding:0;text-align:left;text-transform:none;text-decoration:line-through;}/*!sc*/
data-styled.g1[id="sc-braxZu"]{content:"jEqeKQ,cyPhJl,AgQbP,dughoY,lmmumg,kjFjan,kvfdZL,gbxhkm,"}/*!sc*/
.cebpdv{height:16px;width:16px;fill:#EF6E0B;}/*!sc*/
.iBhqnD{height:20px;width:20px;fill:#EF6E0B;}/*!sc*/
.MZXFH{height:6px;width:6px;fill:#0059A3;}/*!sc*/
.Jtbgc{height:20px;width:20px;fill:none;}/*!sc*/
.kXgPQL{height:var(--icon-size-12);width:var(--icon-size-12);fill:#0059A3;}/*!sc*/
data-styled.g2[id="sc-gJhJTp"]{content:"cebpdv,iBhqnD,MZXFH,Jtbgc,kXgPQL,"}/*!sc*/
.dwoIep{padding:var(--spacing-4) var(--spacing-10);background-color:var(--base-white);border-width:1px;border-style:solid;border-color:var(--grey-200);border-radius:var(--corner-radius-8);display:flex;gap:var(--spacing-4);align-items:center;color:var(--grey-900);transition:transform 0.2s,opacity 0.2s;will-change:transform,opacity;backface-visibility:hidden;}/*!sc*/
.dwoIep:active{transform:scale(0.98);opacity:0.85;}/*!sc*/
.dwoIep:disabled{background-color:var(--grey-50);border:none;color:var(--grey-300);}/*!sc*/
data-styled.g3[id="sc-elDIKY"]{content:"dwoIep,"}/*!sc*/
.khYsVE{display:flex;justify-content:center;align-items:center;width:var(--icon-size-16);height:var(--icon-size-16);}/*!sc*/
data-styled.g4[id="sc-fQpRED"]{content:"khYsVE,"}/*!sc*/
.DVsLB{display:block;font-size:var(--font-size-sm);font-weight:var(--semibold);line-height:var(--font-line-height-lg);color:var(--orange-500);margin:0;padding:0;}/*!sc*/
.cHgkKx{display:block;font-size:var(--font-size-sm);font-weight:var(--regular);line-height:var(--font-line-height-lg);color:var(--grey-900);margin:0;padding:0;}/*!sc*/
.hpYnxU{display:block;font-size:var(--font-size-sm);font-weight:var(--semibold);line-height:var(--font-line-height-lg);color:var(--grey-900);margin:0;padding:0;}/*!sc*/
data-styled.g5[id="sc-dsLQwm"]{content:"DVsLB,cHgkKx,hpYnxU,"}/*!sc*/
.esHUuk{font-size:var(--font-size-base);font-weight:var(--medium);line-height:var(--font-line-height-base);color:var(--grey-900);text-decoration:none;margin:0;padding:0;}/*!sc*/
data-styled.g6[id="sc-iKTcqh"]{content:"esHUuk,"}/*!sc*/
.fPvNdE{position:absolute;opacity:0;width:0;height:0;}/*!sc*/
data-styled.g7[id="sc-gnpbhQ"]{content:"fPvNdE,"}/*!sc*/

In [16]:
km_driven=[]
fuel_type=[]
transmission=[]
RTO=[]
j=soup.find_all('p',class_="sc-braxZu kvfdZL")
for i in j:
    if "km" in i.get_text():
        km=i.get_text()
        km_driven.append(km)
    elif "Diesel" in i.get_text() or "Petrol" in i.get_text() or "CNG" in i.get_text() or "Electric" in i.get_text():
        fuel=i.get_text()
        fuel_type.append(fuel)
    elif "Manual" in i.get_text() or "Auto" in i.get_text():
         t=i.get_text()
         transmission.append(t)
    elif "KA" in i.get_text():
         R=i.get_text()
         RTO.append(R)     
    
print(km_driven)
print(fuel_type)
print(transmission)
print(RTO)
print(len(km_driven),len(fuel_type),len(transmission),len(RTO))

['32.66k km', '64.89k km', '8.18k km', '41.33k km', '70.34k km', '53.13k km', '80.89k km', '56.31k km', '30.99k km', '6.39k km', '78.92k km', '22.91k km', '41.05k km', '99.95k km', '14.68k km', '19.41k km', '44.63k km', '1.1L km', '41.68k km', '59.01k km']
['Petrol', 'Diesel', 'Diesel', 'Petrol', 'Diesel', 'Petrol', 'CNG', 'Petrol', 'Petrol', 'Petrol', 'Petrol', 'Petrol', 'Petrol', 'Petrol', 'Petrol', 'Petrol', 'Petrol', 'Petrol', 'Diesel', 'Petrol']
['Auto', 'Manual', 'Auto', 'Manual', 'Manual', 'Auto', 'Manual', 'Manual', 'Manual', 'Manual', 'Manual', 'Manual', 'Auto', 'Manual', 'Auto', 'Manual', 'Manual', 'Manual', 'Manual', 'Manual']
['KA-03', 'KA-03', 'KA-53', 'KA-02', 'KA-03', 'KA-05', 'KA-02', 'KA-05', 'KA-41', 'KA-05', 'KA-01', 'KA-19', 'KA-03', 'KA-53', 'KA-51', 'KA-53', 'KA-05', 'KA-02', 'KA-51', 'KA-05']
20 20 20 20

In [18]:
carname=[]
name=soup.find_all('span',class_="sc-braxZu kjFjan")
for i in name:
    carname.append(i.text)
print(len(carname)) 
print(carname)

20
['2020 BMW X1', '2021 Tata Safari', '2023 MG GLOSTER', '2013 Maruti Alto 800', '2016 Ford Ecosport', '2020 Maruti Ertiga', '2014 Toyota Etios', '2017 Tata TIGOR', '2018 Hyundai Grand i10', '2018 Maruti Baleno', '2016 Maruti Swift Dzire', '2018 Hyundai Grand i10', '2017 Maruti Wagon R 1.0', '2014 Hyundai i20', '2023 Mahindra XUV700', '2015 Hyundai Grand i10', '2019 Ford Ecosport', '2016 Volkswagen Vento', '2015 Renault Duster', '2013 Hyundai Eon']

In [19]:
price=[]
prices=soup.find_all('p',class_="sc-braxZu cyPhJl")
for i in prices:
    price.append(i.text)
print(len(price))
print(price)

22
['Account ', '', '₹28.45 lakh', '₹16.65 lakh', '₹36.45 lakh', '₹2.19 lakh', '₹5.47 lakh', '₹8.93 lakh', '₹4.00 lakh', '₹4.78 lakh', '₹5.29 lakh', '₹6.29 lakh', '₹5.12 lakh', '₹4.86 lakh', '₹3.97 lakh', '₹4.15 lakh', '₹21.40 lakh', '₹4.04 lakh', '₹7.31 lakh', '₹4.98 lakh', '₹6.13 lakh', '₹1.89 lakh']

In [20]:
car_price=[]
car_price=price[2:22]
print(car_price)
print(len(car_price))

['₹28.45 lakh', '₹16.65 lakh', '₹36.45 lakh', '₹2.19 lakh', '₹5.47 lakh', '₹8.93 lakh', '₹4.00 lakh', '₹4.78 lakh', '₹5.29 lakh', '₹6.29 lakh', '₹5.12 lakh', '₹4.86 lakh', '₹3.97 lakh', '₹4.15 lakh', '₹21.40 lakh', '₹4.04 lakh', '₹7.31 lakh', '₹4.98 lakh', '₹6.13 lakh', '₹1.89 lakh']
20

In [21]:
location=[]
locations=soup.find_all('div',class_="styles_hubAddress__URioy")
for i in locations:
    location.append(i.text)
print(location)
print(len(location))

[' CARS24 ELITE Hub, MS Ramaiah North City', ' CARS24 ELITE Hub, MS Ramaiah North City', ' CARS24 ELITE Hub, MS Ramaiah North City', ' Nexus Whitefield', ' Nexus Whitefield', ' Whitefield Main Road, Bhoruka Tech Park, Bengaluru', ' Gandhi Nagar', ' Gandhi Nagar', ' Nexus Whitefield', ' Bellahalli, Bengaluru', ' Whitefield Main Road, Bhoruka Tech Park, Bengaluru', ' Whitefield Main Road, Bhoruka Tech Park, Bengaluru', ' Bellahalli, Bengaluru', ' Whitefield Main Road, Bhoruka Tech Park, Bengaluru', ' GT World Mall, Bengaluru', ' Bellahalli, Bengaluru', ' GT World Mall, Bengaluru', ' GT World Mall, Bengaluru', ' GT World Mall, Bengaluru', ' GT World Mall, Bengaluru']
20

In [22]:
data=pd.DataFrame({'car_name':carname,'price':car_price,'RTO':RTO,'km_driven':km_driven,'fuel_type':fuel_type,'transmission':transmission,'location':location})
data

,car_name,price,RTO,km_driven,fuel_type,transmission,location
0,2020 BMW X1,₹28.45 lakh,KA-03,32.66k km,Petrol,Auto,"CARS24 ELITE Hub, MS Ramaiah North City"
1,2021 Tata Safari,₹16.65 lakh,KA-03,64.89k km,Diesel,Manual,"CARS24 ELITE Hub, MS Ramaiah North City"
2,2023 MG GLOSTER,₹36.45 lakh,KA-53,8.18k km,Diesel,Auto,"CARS24 ELITE Hub, MS Ramaiah North City"
3,2013 Maruti Alto 800,₹2.19 lakh,KA-02,41.33k km,Petrol,Manual,Nexus Whitefield
4,2016 Ford Ecosport,₹5.47 lakh,KA-03,70.34k km,Diesel,Manual,Nexus Whitefield
5,2020 Maruti Ertiga,₹8.93 lakh,KA-05,53.13k km,Petrol,Auto,"Whitefield Main Road, Bhoruka Tech Park, Beng..."
6,2014 Toyota Etios,₹4.00 lakh,KA-02,80.89k km,CNG,Manual,Gandhi Nagar
7,2017 Tata TIGOR,₹4.78 lakh,KA-05,56.31k km,Petrol,Manual,Gandhi Nagar
8,2018 Hyundai Grand i10,₹5.29 lakh,KA-41,30.99k km,Petrol,Manual,Nexus Whitefield
9,2018 Maruti Baleno,₹6.29 lakh,KA-05,6.39k km,Petrol,Manual,"Bellahalli, Bengaluru"
10,2016 Maruti Swift Dzire,₹5.12 lakh,KA-01,78.92k km,Petrol,Manual,"Whitefield Main Road, Bhoruka Tech Park, Beng..."
11,2018 Hyundai Grand i10,₹4.86 lakh,KA-19,22.91k km,Petrol,Manual,"Whitefield Main Road, Bhoruka Tech Park, Beng..."
12,2017 Maruti Wagon R 1.0,₹3.97 lakh,KA-03,41.05k km,Petrol,Auto,"Bellahalli, Bengaluru"
13,2014 Hyundai i20,₹4.15 lakh,KA-53,99.95k km,Petrol,Manual,"Whitefield Main Road, Bhoruka Tech Park, Beng..."
14,2023 Mahindra XUV700,₹21.40 lakh,KA-51,14.68k km,Petrol,Auto,"GT World Mall, Bengaluru"
15,2015 Hyundai Grand i10,₹4.04 lakh,KA-53,19.41k km,Petrol,Manual,"Bellahalli, Bengaluru"
16,2019 Ford Ecosport,₹7.31 lakh,KA-05,44.63k km,Petrol,Manual,"GT World Mall, Bengaluru"
17,2016 Volkswagen Vento,₹4.98 lakh,KA-02,1.1L km,Petrol,Manual,"GT World Mall, Bengaluru"
18,2015 Renault Duster,₹6.13 lakh,KA-51,41.68k km,Diesel,Manual,"GT World Mall, Bengaluru"
19,2013 Hyundai Eon,₹1.89 lakh,KA-05,59.01k km,Petrol,Manual,"GT World Mall, Bengaluru"

In [23]:
data.to_csv('cars24_bangalore.csv')

In [24]:
url='https://www.cars24.com/buy-used-cars-new-delhi/'
r=requests.get(url)
response=r.status_code
response

200

In [25]:
soup=BeautifulSoup(r.content,'html5lib')
soup

<!DOCTYPE html>

In [26]:
location=[]
locations=soup.find_all('div',class_="styles_hubAddress__URioy")
for i in locations:
    location.append(i.text)
print(location)
print(len(location))

[' Metro Walk, Rohini, New Delhi', ' Rajouri Garden', ' Metro Walk, Rohini, New Delhi', ' Metro Walk, Rohini, New Delhi', ' Metro Walk, Rohini, New Delhi', ' Metro Walk, Rohini, New Delhi', ' Metro Walk, Rohini, New Delhi', ' Metro Walk, Rohini, New Delhi', ' Rajouri Garden', ' Metro Walk, Rohini, New Delhi', ' Metro Walk, Rohini, New Delhi', ' Metro Walk, Rohini, New Delhi', ' Rajouri Garden', ' Metro Walk, Rohini, New Delhi', ' Rajouri Garden', ' Metro Walk, Rohini, New Delhi', ' Metro Walk, Rohini, New Delhi', ' Rajouri Garden', ' Metro Walk, Rohini, New Delhi', ' Rajouri Garden', ' CARS24 ELITE Hub, Surajpur Site-4, Greater Noida', ' CARS24 ELITE Hub, Surajpur Site-4, Greater Noida', ' KW Delhi 6, Raj Nagar Extension, Ghaziabad', ' M3M Urbana, Golf Course Ext., Gurugram', ' CARS24 ELITE Hub, Malibu Town, Sector 47', ' CARS24 ELITE Hub, Surajpur Site-4, Greater Noida', ' CARS24 ELITE Hub, Surajpur Site-4, Greater Noida', ' Udyog Vihar, Sector 18, Gurgaon', ' CARS24 ELITE Hub, Malibu Town, Sector 47', ' CARS24 ELITE Hub, Malibu Town, Sector 47', ' CARS24 ELITE Hub, Malibu Town, Sector 47', ' CARS24 ELITE Hub, Malibu Town, Sector 47', ' CARS24 ELITE Hub, Surajpur Site-4, Greater Noida', ' CARS24 ELITE Hub, Surajpur Site-4, Greater Noida', ' Piyush Mahendra Mall, opp. Dussehra Ground, NIT - 3', ' Piyush Mahendra Mall, opp. Dussehra Ground, NIT - 3', ' CARS24 ELITE Hub, Malibu Town, Sector 47', ' M3M Urbana, Golf Course Ext., Gurugram', ' CARS24 ELITE Hub, Malibu Town, Sector 47', ' CARS24 ELITE Hub, Surajpur Site-4, Greater Noida']
40

In [27]:
km_driven=[]
fuel_type=[]
transmission=[]
RTO=[]
j=soup.find_all('p',class_="sc-braxZu kvfdZL")
for i in j:
    if "km" in i.get_text():
        km=i.get_text()
        km_driven.append(km)
    elif "Diesel" in i.get_text() or "Petrol" in i.get_text() or "CNG" in i.get_text() or "Electric" in i.get_text():
        fuel=i.get_text()
        fuel_type.append(fuel)
    elif "Manual" in i.get_text() or "Auto" in i.get_text():
         t=i.get_text()
         transmission.append(t)
    elif "DL" in i.get_text() or "HR" in i.get_text() or "UP" in i.get_text():
         R=i.get_text()
         RTO.append(R)     
    
print(km_driven)
print(fuel_type)
print(transmission)
print(RTO)
print(len(km_driven),len(fuel_type),len(transmission),len(RTO))

['51.55k km', '61.73k km', '33.21k km', '57.13k km', '23.67k km', '56.79k km', '67.82k km', '43.05k km', '37.13k km', '36.56k km', '57.64k km', '65.67k km', '63.85k km', '48.78k km', '1.3L km', '53.31k km', '71.29k km', '88.40k km', '31.96k km', '30.43k km', '38.94k km', '29.00k km', '99.90k km', '1.3L km', '35.94k km', '17.40k km', '16.31k km', '71.10k km', '17.56k km', '49.32k km', '17.33k km', '24.19k km', '12.35k km', '7.68k km', '75.80k km', '57.79k km', '3.24k km', '57.57k km', '79.81k km', '67.29k km']
['Petrol', 'Petrol', 'Petrol', 'Petrol', 'Petrol', 'Petrol', 'Petrol', 'Petrol', 'Petrol', 'Petrol', 'Petrol', 'Petrol', 'Petrol', 'Petrol', 'Petrol', 'Petrol', 'Petrol', 'Petrol', 'Petrol', 'Petrol', 'Diesel', 'Petrol', 'Petrol', 'Petrol', 'Petrol', 'Petrol', 'Petrol', 'CNG', 'Petrol', 'Diesel', 'Diesel', 'Diesel', 'Petrol', 'Petrol', 'Diesel', 'Petrol', 'Electric', 'Diesel', 'Diesel', 'Diesel']
['Manual', 'Manual', 'Manual', 'Manual', 'Manual', 'Auto', 'Manual', 'Manual', 'Manual', 'Manual', 'Manual', 'Auto', 'Manual', 'Manual', 'Manual', 'Manual', 'Manual', 'Manual', 'Manual', 'Auto', 'Auto', 'Auto', 'Manual', 'Manual', 'Auto', 'Manual', 'Auto', 'Manual', 'Manual', 'Auto', 'Auto', 'Auto', 'Auto', 'Auto', 'Manual', 'Manual', 'Auto', 'Manual', 'Auto', 'Manual']
['DL-12', 'DL-7C', 'DL-5C', 'DL-4C', 'HR-02', 'DL-3C', 'DL-8C', 'DL-10', 'DL-5C', 'DL-1C', 'DL-8C', 'DL-2C', 'DL-10', 'DL-3C', 'DL-7C', 'HR-51', 'DL-2C', 'DL-14', 'DL-7C', 'DL-12', 'UP-16', 'HR-98', 'DL-3C', 'HR-26', 'HR-87', 'DL-3C', 'DL-3C', 'HR-12', 'HR-85', 'HR-13', 'HR-29', 'HR-51', 'HR-98', 'HR-98', 'HR-29', 'HR-87', 'DL-1G', 'HR-26', 'HR-87', 'DL-3C']
40 40 40 40

In [28]:
carname=[]
name=soup.find_all('span',class_="sc-braxZu kjFjan")
for i in name:
    carname.append(i.text)
print(len(carname)) 
print(carname)

40
['2012 Maruti Wagon R 1.0', '2021 Nissan MAGNITE', '2023 Tata PUNCH', '2020 Hyundai VENUE', '2019 Hyundai Elite i20', '2023 Maruti FRONX', '2016 Hyundai Elite i20', '2020 MG HECTOR', '2017 Hyundai Eon', '2018 Hyundai Grand i10', '2021 Volkswagen Polo', '2020 Jeep Compass', '2019 Tata NEXON', '2019 Maruti New Wagon-R', '2018 Hyundai Grand i10', '2017 Tata TIGOR', '2021 Maruti Ertiga', '2017 Honda City', '2022 Mahindra Thar', '2019 Hyundai NEW SANTRO', '2023 Mahindra Thar', '2024 Hyundai Creta', '2018 Datsun Go', '2019 Toyota Innova Crysta', '2022 KIA SELTOS', '2022 KIA SELTOS', '2022 Jeep Compass', '2022 MG ASTOR', '2022 Mahindra SCORPIO-N', '2019 Landrover DISCOVERY SPORT', '2022 Mercedes Benz GLA Class', '2022 Mercedes Benz GLS', '2024 Hyundai Creta', '2024 Hyundai Creta', '2019 Renault Duster', '2022 Renault Kiger', '2023 BMW iX', '2022 Jeep Compass', '2021 KIA CARNIVAL', '2022 Mahindra XUV700']

In [29]:
price=[]
prices=soup.find_all('p',class_="sc-braxZu cyPhJl")
for i in prices:
    price.append(i.text)
print(len(price))
print(price)

42
['Account ', '', '₹1.52 lakh', '₹4.12 lakh', '₹4.75 lakh', '₹5.53 lakh', '₹4.76 lakh', '₹7.38 lakh', '₹3.69 lakh', '₹8.44 lakh', '₹2.16 lakh', '₹3.28 lakh', '₹4.75 lakh', '₹10.43 lakh', '₹5.63 lakh', '₹3.60 lakh', '₹3.22 lakh', '₹3.16 lakh', '₹7.99 lakh', '₹5.55 lakh', '₹10.59 lakh', '₹3.74 lakh', '₹15.00 lakh', '₹17.30 lakh', '₹1.95 lakh', '₹10.64 lakh', '₹14.00 lakh', '₹12.90 lakh', '₹19.00 lakh', '₹7.40 lakh', '₹19.00 lakh', '₹29.00 lakh', '₹39.00 lakh', '₹1.00 Crore', '₹18.40 lakh', '₹18.35 lakh', '₹5.11 lakh', '₹4.79 lakh', '₹75.00 lakh', '₹14.96 lakh', '₹20.90 lakh', '₹14.25 lakh']

In [30]:
car_price=[]
car_price=price[2:42]
print(car_price)
print(len(car_price))

['₹1.52 lakh', '₹4.12 lakh', '₹4.75 lakh', '₹5.53 lakh', '₹4.76 lakh', '₹7.38 lakh', '₹3.69 lakh', '₹8.44 lakh', '₹2.16 lakh', '₹3.28 lakh', '₹4.75 lakh', '₹10.43 lakh', '₹5.63 lakh', '₹3.60 lakh', '₹3.22 lakh', '₹3.16 lakh', '₹7.99 lakh', '₹5.55 lakh', '₹10.59 lakh', '₹3.74 lakh', '₹15.00 lakh', '₹17.30 lakh', '₹1.95 lakh', '₹10.64 lakh', '₹14.00 lakh', '₹12.90 lakh', '₹19.00 lakh', '₹7.40 lakh', '₹19.00 lakh', '₹29.00 lakh', '₹39.00 lakh', '₹1.00 Crore', '₹18.40 lakh', '₹18.35 lakh', '₹5.11 lakh', '₹4.79 lakh', '₹75.00 lakh', '₹14.96 lakh', '₹20.90 lakh', '₹14.25 lakh']
40

In [31]:
data=pd.DataFrame({'car_name':carname,'price':car_price,'RTO':RTO,'km_driven':km_driven,'fuel_type':fuel_type,'transmission':transmission,'location':location})
data

,car_name,price,RTO,km_driven,fuel_type,transmission,location
0,2012 Maruti Wagon R 1.0,₹1.52 lakh,DL-12,51.55k km,Petrol,Manual,"Metro Walk, Rohini, New Delhi"
1,2021 Nissan MAGNITE,₹4.12 lakh,DL-7C,61.73k km,Petrol,Manual,Rajouri Garden
2,2023 Tata PUNCH,₹4.75 lakh,DL-5C,33.21k km,Petrol,Manual,"Metro Walk, Rohini, New Delhi"
3,2020 Hyundai VENUE,₹5.53 lakh,DL-4C,57.13k km,Petrol,Manual,"Metro Walk, Rohini, New Delhi"
4,2019 Hyundai Elite i20,₹4.76 lakh,HR-02,23.67k km,Petrol,Manual,"Metro Walk, Rohini, New Delhi"
5,2023 Maruti FRONX,₹7.38 lakh,DL-3C,56.79k km,Petrol,Auto,"Metro Walk, Rohini, New Delhi"
6,2016 Hyundai Elite i20,₹3.69 lakh,DL-8C,67.82k km,Petrol,Manual,"Metro Walk, Rohini, New Delhi"
7,2020 MG HECTOR,₹8.44 lakh,DL-10,43.05k km,Petrol,Manual,"Metro Walk, Rohini, New Delhi"
8,2017 Hyundai Eon,₹2.16 lakh,DL-5C,37.13k km,Petrol,Manual,Rajouri Garden
9,2018 Hyundai Grand i10,₹3.28 lakh,DL-1C,36.56k km,Petrol,Manual,"Metro Walk, Rohini, New Delhi"
10,2021 Volkswagen Polo,₹4.75 lakh,DL-8C,57.64k km,Petrol,Manual,"Metro Walk, Rohini, New Delhi"
11,2020 Jeep Compass,₹10.43 lakh,DL-2C,65.67k km,Petrol,Auto,"Metro Walk, Rohini, New Delhi"
12,2019 Tata NEXON,₹5.63 lakh,DL-10,63.85k km,Petrol,Manual,Rajouri Garden
13,2019 Maruti New Wagon-R,₹3.60 lakh,DL-3C,48.78k km,Petrol,Manual,"Metro Walk, Rohini, New Delhi"
14,2018 Hyundai Grand i10,₹3.22 lakh,DL-7C,1.3L km,Petrol,Manual,Rajouri Garden
15,2017 Tata TIGOR,₹3.16 lakh,HR-51,53.31k km,Petrol,Manual,"Metro Walk, Rohini, New Delhi"
16,2021 Maruti Ertiga,₹7.99 lakh,DL-2C,71.29k km,Petrol,Manual,"Metro Walk, Rohini, New Delhi"
17,2017 Honda City,₹5.55 lakh,DL-14,88.40k km,Petrol,Manual,Rajouri Garden
18,2022 Mahindra Thar,₹10.59 lakh,DL-7C,31.96k km,Petrol,Manual,"Metro Walk, Rohini, New Delhi"
19,2019 Hyundai NEW SANTRO,₹3.74 lakh,DL-12,30.43k km,Petrol,Auto,Rajouri Garden
20,2023 Mahindra Thar,₹15.00 lakh,UP-16,38.94k km,Diesel,Auto,"CARS24 ELITE Hub, Surajpur Site-4, Greater Noida"
21,2024 Hyundai Creta,₹17.30 lakh,HR-98,29.00k km,Petrol,Auto,"CARS24 ELITE Hub, Surajpur Site-4, Greater Noida"
22,2018 Datsun Go,₹1.95 lakh,DL-3C,99.90k km,Petrol,Manual,"KW Delhi 6, Raj Nagar Extension, Ghaziabad"
23,2019 Toyota Innova Crysta,₹10.64 lakh,HR-26,1.3L km,Petrol,Manual,"M3M Urbana, Golf Course Ext., Gurugram"
24,2022 KIA SELTOS,₹14.00 lakh,HR-87,35.94k km,Petrol,Auto,"CARS24 ELITE Hub, Malibu Town, Sector 47"
25,2022 KIA SELTOS,₹12.90 lakh,DL-3C,17.40k km,Petrol,Manual,"CARS24 ELITE Hub, Surajpur Site-4, Greater Noida"
26,2022 Jeep Compass,₹19.00 lakh,DL-3C,16.31k km,Petrol,Auto,"CARS24 ELITE Hub, Surajpur Site-4, Greater Noida"
27,2022 MG ASTOR,₹7.40 lakh,HR-12,71.10k km,CNG,Manual,"Udyog Vihar, Sector 18, Gurgaon"
28,2022 Mahindra SCORPIO-N,₹19.00 lakh,HR-85,17.56k km,Petrol,Manual,"CARS24 ELITE Hub, Malibu Town, Sector 47"
29,2019 Landrover DISCOVERY SPORT,₹29.00 lakh,HR-13,49.32k km,Diesel,Auto,"CARS24 ELITE Hub, Malibu Town, Sector 47"
30,2022 Mercedes Benz GLA Class,₹39.00 lakh,HR-29,17.33k km,Diesel,Auto,"CARS24 ELITE Hub, Malibu Town, Sector 47"
31,2022 Mercedes Benz GLS,₹1.00 Crore,HR-51,24.19k km,Diesel,Auto,"CARS24 ELITE Hub, Malibu Town, Sector 47"
32,2024 Hyundai Creta,₹18.40 lakh,HR-98,12.35k km,Petrol,Auto,"CARS24 ELITE Hub, Surajpur Site-4, Greater Noida"
33,2024 Hyundai Creta,₹18.35 lakh,HR-98,7.68k km,Petrol,Auto,"CARS24 ELITE Hub, Surajpur Site-4, Greater Noida"
34,2019 Renault Duster,₹5.11 lakh,HR-29,75.80k km,Diesel,Manual,"Piyush Mahendra Mall, opp. Dussehra Ground, N..."
35,2022 Renault Kiger,₹4.79 lakh,HR-87,57.79k km,Petrol,Manual,"Piyush Mahendra Mall, opp. Dussehra Ground, N..."
36,2023 BMW iX,₹75.00 lakh,DL-1G,3.24k km,Electric,Auto,"CARS24 ELITE Hub, Malibu Town, Sector 47"
37,2022 Jeep Compass,₹14.96 lakh,HR-26,57.57k km,Diesel,Manual,"M3M Urbana, Golf Course Ext., Gurugram"
38,2021 KIA CARNIVAL,₹20.90 lakh,HR-87,79.81k km,Diesel,Auto,"CARS24 ELITE Hub, Malibu Town, Sector 47"
39,2022 Mahindra XUV700,₹14.25 lakh,DL-3C,67.29k km,Diesel,Manual,"CARS24 ELITE Hub, Surajpur Site-4, Greater Noida"

In [32]:
data.to_csv('cars24_delhi.csv')